version: "3.7"
services:

  esmaster1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    ports:
        - "9200:9200"
    environment:
      - cluster.name=apmpoc
      - discovery.type=single-node
      - node.name=master1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.zen.ping.unicast.hosts=esmaster1
      - node.data=true
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esmaster1:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://esmaster1:9200
      SERVER_HOST: "0.0.0.0"
#      xpack.monitoring.elasticsearch.url: http://eshealth:9200
      #- "xpack.security.enabled=false"
#      xpack.ml.enabled: false
      #- "xpack.reporting.enabled=false"
      #- "elasticsearch.url=esmaster1:9200"

  #
  apmserver:
    image: docker.elastic.co/apm/apm-server:7.1.0
    ports:
        - "8200:8200"
    volumes:
        - ./apm_server/apm-server.yml:/usr/share/apm-server/apm-server.yml/

volumes:
  esmaster1:
    driver: local
